In [ ]:
# Data Frame: 

# A DataFrame is a 2-dimensional labeled data structure in Pandas that stores data in rows and columns (like a table in Excel).
# When we combine two or more series it becomes data frame.

In [1]:
# What we are gonna learn in it: 

# Creating data frames 
# Selection and indexing of columns 
# Creating a new column 
# Removing column 
# Removing row 
# Selecting row 
# Selecting subsets of rows and columns 
# Conditional selection

In [69]:
import numpy as np 
import pandas as pd

In [5]:
# Creating data frames: 

data = {
    'Name': ['John' , 'Anna' , 'Peter' , 'Linda'] ,
    'Age': [28 , 34 , 29 , 42] ,
    'City': ['New York' , 'Paris' , 'Berlin' , 'London'] ,
    'Salary': [65000 , 70000 , 62000 , 85000]    
}

df = pd.DataFrame(data)

In [6]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
data_list = [
    ['John' , 28 , 'New York' , 65000],
    ['Anna' , 34 , 'Paris' , 70000],
    ['Peter' , 29 , 'Berlin' , 62000],
    ['Linda' , 42 , 'London' , 85000]
]

columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)

In [21]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# Selection and Indexing of Columns:

In [24]:
df2['Name'] # In indexing of columns in data frame didnt works the same like array index in data frame we have to name the column to get its data 
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [25]:
df2[["Name" , "City"]] # If you want to get a two or multiple columns then create list of a list and then provide the columns names

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [30]:
# Creating a column inside a data frame:  

df2["Designation"] = ["Doctor" , "Software engineer" , "Doctor" , "Software engineer"] # This will create a new column at the end of the datafram 
# index and and df2["Designation"] means create a new column inside df2 data frame and then ["Doctor",...] means the values inside it be carefull 
# provide the exact number of values which all the columns have if you disturb the count it will throw an error.  
df2

    Name  Age      City  Salary        Designation
0   John   28  New York   65000             Doctor
1   Anna   34     Paris   70000  Software engineer
2  Peter   29    Berlin   62000             Doctor
3  Linda   42    London   85000  Software engineer

In [46]:
# Removing a column inside a data frame 

df2.drop(['City' , 'Age'] , axis=1 , inplace=False)

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [47]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [48]:
# Removing rows:  
df2.drop(0,axis=0) # When you want to remove the row then do nothing just say its index value.

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [49]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [51]:
# Selection of the rows: 

# df2[0] # This will throw the keyerror. 

# Right way is: 

df2.loc[0] # loc means location and it will select 0 location index of the row

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [52]:
# If you want to select multiple rows then create list of list and provide the index: 

df2.loc[[0,3]]

    Name  Age      City  Salary
0   John   28  New York   65000
3  Linda   42    London   85000

In [59]:
# Selecting subsets of rows and columns: 

df2.loc[[0 , 1],["City" , "Salary"]] # You need to provide the the index of dataframe inside a list and then in other list provide the column 
                                     # key. 

df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [60]:
df2.loc[[2,3],["Name" , "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [ ]:
# Conditional selection: 

# Conditional selection means Selecting rows or data from a DataFrame based on a condition.

# for example i only want to see the people who's age is greater than 30:

In [61]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
# The age must be greater than 30 and the city must be paris only

In [63]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

In [64]:
df2[df2["Salary"] < 80000]

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

In [68]:
conditionalChecking = df2[ (df2["Salary"] < 70000) & (df2["Age"] < 30) ] # If you want to do and or and not operation then you 
# you just put each condition in paranthesis( () ). 
conditionalChecking

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000