In [ ]:
# Group by and aggregation: 

# Group By:
# Group by is a process of dividing data into groups based on a common value or key, so that each group contains similar items together.

# Aggregation:
# Aggregation is the process of performing a mathematical or statistical operation on each group of data,
# such as sum, mean, count, max, or min, to get a single summarized result for each group.

In [2]:
import numpy as np 
import pandas as pd

In [3]:
# data: 

data = {
    'Category': ['A','B','A','B', 'A','B', 'A','B',], 
    'Store': ['S1','S1', 'S2' ,'S2' , 'S1' , 'S2' , 'S2' , 'S1'], 
    'Sales': [100 , 200 , 150 ,250 , 120 , 180 , 200 , 300] ,
    'Quantity': [10 , 15 ,12 , 18 , 8 , 20 , 15 , 25] , 
    'Date': pd.date_range('2023-01-01' , periods=8)
}
df = pd.DataFrame(data) 
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [6]:
# Group by category and calculate the sum: 

cat = df.groupby('Category')['Sales'].sum()

cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [7]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [6]:
# Group by stores and calculate the sum of the sales:

salesSumOfStore = df.groupby('Store')['Sales'].sum() 

salesSumOfStore

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [8]:
# Group by multiple columns: 
# Group by Category and stores:

groupByCandS = df.groupby(['Category','Store'])['Sales'].sum()
groupByCandS

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [9]:
# Aggregation:

In [13]:
# For example: 

df["Sales"].mean()


""" mode , median , mean , min , max , count , std """ # These are aggregation functions.

np.float64(187.5)

In [25]:
df["Sales"].agg(["min" , "min" , 'mean']) # Mode will not work in list thats an issue, if u want mode simply find it separately

min     100.0
min     100.0
mean    187.5
Name: Sales, dtype: float64