In [ ]:
# Missing Data: 

# Missing data means Values that are empty, unavailable, or not recorded in a DataFrame. 

# What we are going to study: 

# Finding missing data 
# Removing missing data 
# Filling missing data

In [4]:
import numpy as np 
import pandas as pd

In [10]:
data = {
    'A': [1 , 2 , np.nan , 4 , 5] , 
    'B': [np.nan , 2 , 3 , 4 , 5] ,
    'C': [1 , 2 , 3 , np.nan , np.nan] , 
    'D': [1 , np.nan , np.nan , np.nan , 5] ,
}

df = pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [20]:
# If we want to check that its number or we have to write function np.isna()

df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [16]:
# This will give you the count of null value inside each column 

df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [19]:
# This will the rows and will answer you true if there's any null value in a column 

df.isna().any() # you can provide the axis=0 or axis=1 according to row or column need, 0 for rows and 1 for co.

A    True
B    True
C    True
D    True
dtype: bool

In [ ]:
# Removing Missing data from data frame: 

# Removing missing data means: Deleting rows or columns that contain missing values (NaN or None) from a DataFrame.

In [30]:
# Apply this function if you want to remove all the nan from your data framework: 
df = pd.DataFrame(data)
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [32]:
df.dropna(thresh=3) # thresh means minimum number of non-missing (non-NaN) values required to keep a row or column

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
# Filling missing data of a data frame: 

# Filling missing data means Replacing missing values (NaN or None) in a DataFrame with some meaningful value instead of deleting them.

In [34]:
# for example: 

# If you want to fill all the na values of a data frame then do this: 

df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [33]:
# for example: 

# If you want to fill the value of na column wise then do this: 

values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  400.0
2  0.0    3.0    3.0  400.0
3  4.0    4.0  300.0  400.0
4  5.0    5.0  300.0    5.0

In [35]:
values2 = {'A':10,'B':20,'C':30,'D':40}
df.fillna(value=values2)

      A     B     C     D
0   1.0  20.0   1.0   1.0
1   2.0   2.0   2.0  40.0
2  10.0   3.0   3.0  40.0
3   4.0   4.0  30.0  40.0
4   5.0   5.0  30.0   5.0