# Import Basic Libraries

> Like numpy, pandas, matplotlib, seaborn and filter warnings

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

# Loading DataSet

> We have the data in .txt file not in csv file

> The row values are separated by ; so we will also seperate it using columns

> Its txt file so we have to give me columns name by ourself as well

> In end we will check wheter the changes applies on the data or not

In [7]:
df: pd.DataFrame = pd.read_csv('train.txt', sep=';', header=None, names=['text', 'emotion'])

In [8]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

# Check Null Values

> Null values can harm our ML model alot

> It can reduce model's accuracy becuase ML models cant process it we will get error like: **ValueError: Input contains NaN**

In [9]:
df.isnull().sum() # No null values detected so our data is ready for encoding

text       0
emotion    0
dtype: int64

# Check (n) Unique Emotion Values

> We will check that how much unique values are there in emotions

> We will the actual labels(values) as well of nunique emotions

In [10]:
df['emotion'].nunique()

6

In [11]:
unique_emotions : np.array = df['emotion'].unique()

In [12]:
unique_emotions

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

# Label Encoding - Converting Text To Numbers

# What this code does:

> Finds all unique emotions in the dataset using .unique()

> Assigns a number (0, 1, 2, ...) to each unique emotion using a loop

> Replaces text labels with numbers using .map() so the model can understand them

# Why we do this:

> Machine Learning models work with numbers, not text - they can't process strings like "happy" or "sad"

> Keeps the original meaning - same emotions get the same number, different emotions get different number

In [13]:
emotion_numbers: dict = {}
i: int = 0

for emotion in unique_emotions:
    emotion_numbers[emotion] = i
    i += 1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [14]:
df['emotion'].unique()

array([0, 1, 2, 3, 4, 5])

# Text Normalization - Lowercasing, Punctuation, Digit & ASCII Removal

# What this does:

> Converts all text to lowercase so the model treats similar words the same way. Removes punctuation marks so the model focuses on words instead of symbols. Removes all digits so the model focuses on text rather than numbers. Removes non-ASCII characters so the model only keeps standard English characters.

# Why we do this:

> Reduces vocabulary size and prevents the model from treating the same words differently. Removes unnecessary noise like punctuation, numbers, emojis, and special characters that don't add meaning for most NLP tasks. Standardizes text for consistent processing. Improves model performance by helping it focus on meaning rather than case, symbols, digits, or special characters.

In [15]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [16]:
df['text'].head()

0                              i didnt feel humiliated
1    i can go from feeling so hopeless to so damned...
2     im grabbing a minute to post i feel greedy wrong
3    i am ever feeling nostalgic about the fireplac...
4                                 i am feeling grouchy
Name: text, dtype: object

In [17]:
import string

def remove_punctuations(text: str) -> str:
    if not text:                    # If empty
        return ""                   # Return empty string
    if not isinstance(text, str):   # If not string
        text = str(text)            # Convert it
    return text.translate(str.maketrans('', '', string.punctuation))

In [18]:
# This is an example to understand the above function so get it

# Create a table that says: Replace 'a' with 'x', 'e' with '3'
table = str.maketrans('ae', 'x3')

text = "apple"
result = text.translate(table)
print(result)  # "xppl3"

# What happened?
# 'a' → 'x'
# 'p' → 'p' (no change)
# 'p' → 'p' (no change)
# 'l' → 'l' (no change)
# 'e' → '3'

xppl3

In [19]:
df['text'].apply(remove_punctuations) # Applying the function at text finally

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: object

In [20]:
def remove_digit(text: str) -> str:
  if not text:
    return ""
  if not isinstance(text, str):
    text = str(text)
  return ''.join([i for i in text if not i.isdigit()])

In [21]:
df['text'] = df['text'].apply(remove_digit)

In [22]:
df['text'].head()

0                              i didnt feel humiliated
1    i can go from feeling so hopeless to so damned...
2     im grabbing a minute to post i feel greedy wrong
3    i am ever feeling nostalgic about the fireplac...
4                                 i am feeling grouchy
Name: text, dtype: object

In [23]:
def remove_emojis(text: str) -> str:
  if not text:
    return ""
  if not isinstance(text,str):
    text = str(text)
  return ''.join(filter(lambda x: x.isascii(), text))

In [24]:
df['text'] = df['text'].apply(remove_emojis)

# NLTK(Natural Language Tool Kit)

> NLTK is a leading platform for building Python programs to work
with human language data. It provides easy-to-use interfaces to over 50
corpora and lexical resources such as WordNet, along with a suite of text
processing libraries for classification, tokenization, stemming, tagging,
parsing, and semantic reasoning, wrappers for industrial-strength
NLP libraries, and an active discussion forum.


> Go https://www.nltk.org/ here and study about it and you can also visit
https://spacy.io/ as its also very good for natural language, try to implement
scapy results with nltk and tell me on my github

> In this section, we will tokenize the text and remove the stop words.

In [25]:
import nltk

In [26]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [27]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [28]:
stop_words = set(stopwords.words('english'))

In [29]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [30]:
df.loc[1]['text'] # You can see which words will remove when we will be removing
# stop words

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [40]:
def remove_stopwords(text: str) -> str:
  if not text:
    return ""
  if not isinstance(text, str):
    text = str(text)
  words = word_tokenize(text)
  return ''.join([word for word in words if word.lower() not in stop_words])

In [41]:

import nltk

# Download the most commonly used resources
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

df['text'].apply(remove_stopwords)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

0                                      didntfeelhumiliated
1        gofeelinghopelessdamnedhopefularoundsomeonecar...
2                      imgrabbingminutepostfeelgreedywrong
3           everfeelingnostalgicfireplaceknowstillproperty
4                                           feelinggrouchy
                               ...
15995               brieftimebeanbagsaidannafeellikebeaten
15996    turningfeelpatheticstillwaitingtablessubbingte...
15997                                feelstronggoodoverall
15998                            feellikerudecommentimglad
15999                             knowlotfeelstupidportray
Name: text, Length: 16000, dtype: object

# Bag Of Words

> Bag of Words (BoW) is a technique used to convert text data into numerical vectors based on word counts — completely ignoring grammar and word order.

In [43]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

In [49]:
vectorizer = CountVectorizer(
    max_features=1000,        # ← CRUCIAL! Keep only top 1000 words
    min_df=5,                 # ← Ignore rare words
    max_df=0.7,               # ← Ignore very common words
    stop_words='english',     # ← Remove stopwords
    lowercase=True
)
X = vectorizer.fit_transform(df['text'])

In [50]:
# Convert to array (optional, for viewing)
X_array = X.toarray()

# Get feature names (vocabulary)
feature_names = vectorizer.get_feature_names_out()

# Create a DataFrame with the BoW features
bow_df = pd.DataFrame(X_array, columns=feature_names)

print("Vocabulary size:", len(feature_names))
print("BoW Matrix shape:", X.shape)
bow_df.head()

Vocabulary size: 1000
BoW Matrix shape: (16000, 1000)

,ability,able,absolutely,abused,acceptable,accepted,aching,act,actually,add,...,wrong,wronged,wrote,www,year,years,yes,yesterday,young,youre
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Creating Model

> I will create on model not so much becasue its not a project i am teaching you NLP

In [51]:
# BoW matrix
X = vectorizer.fit_transform(df['text'])
y = df['emotion']

# Now you can train models
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = MultinomialNB()
model.fit(X_train, y_train)

print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.8440625

In [55]:
# Reverse mapping
emotion_labels = {
    0: 'sadness',
    1: 'anger',
    2: 'love',
    3: 'surprise',
    4: 'fear',
    5: 'joy'
}

new_text = ["I feel so happy and excited today!"]
new_text_bow = vectorizer.transform(new_text)
prediction = model.predict(new_text_bow)[0]

print(f"Predicted emotion: {emotion_labels[prediction]}")
# Output: Predicted emotion: joy

Predicted emotion: joy